### ISSUE TITLE
URL parameters

### ISSUE THREAD

**Issue by TonyE73** [ABN-SFLookupTechnicalSupport/ABNLookupSampleCode#3]
What parameters need to be passed with the url for additional information such as trading address, trading name etc. I can't find the info anywhere.

**Comment by ABN-SFLookupTechnicalSupport** [comment]
Hi TonyE73,

Trading addresses are considered private data, and is not accessible to users unless they are a government organisation. Check out this link for more details:
https://abr.business.gov.au/Help/GovernmentAgencies

Trading names are being retired on 31 October 2023 and we strongly advise users to consider searching by other methods rather than just trading names. However if you wish to only search by trading name you can check out our documentation here:
https://abr.business.gov.au/Documentation/WebServiceMethods

In the example below it is this string which allows you to search by trading name "&tradingName=Y" 

https://abr.business.gov.au/abrxmlsearch/AbrXmlSearch.asmx/ABRSearchByNameAdvancedSimpleProtocol2017?name=Searchterm&postcode=&legalName=N&tradingName=Y&businessName=n&activeABNsOnly=N&NSW=y&SA=y&ACT=y&VIC=y&WA=y&NT=y&QLD=y&TAS=y&authenticationGuid=yourGUID&searchWidth=narrow&minimumScore=0&maxSearchResults=10
